import { ArrowLeft, CheckCircle2, MessageCircleMore, Send, ShieldCheck } from "lucide-react";
import Link from "next/link";
import { MerchantSalesAgent } from "@/components/merchant-sales-agent";
import { merchants } from "@/lib/demo-data";

export default async function MerchantReplyDemoPage({ params }: { params: Promise<{ merchantId: string }> }) {
  const { merchantId } = await params;
  const merchant = merchants.find((item) => item.id === merchantId) ?? merchants[2];
  const fields = [["Product / SKU", "WorkFlex Ergo · WFE-820"], ["Available stock", "820 units"], ["Unit price", "₹8,250 before GST"], ["Delivery", "7 business days"], ["Warranty", "3 years"], ["Final payable", "₹41,25,000 incl. GST"]];
  return <main className="min-h-screen bg-slate-50 px-5 py-8 text-slate-800"><div className="mx-auto max-w-3xl"><Link href={`/demo/merchant/${merchant.id}`} className="inline-flex items-center gap-1.5 text-sm font-bold text-slate-500 hover:text-slate-900"><ArrowLeft size={16} /> Merchant request inbox</Link><section className="mt-7 overflow-hidden rounded-[26px] border border-slate-200 bg-white shadow-soft"><header className="bg-slate-900 px-6 py-5 text-white"><p className="text-xs font-bold uppercase tracking-wider text-blue-300">Merchant response · step 2 of 2</p><h1 className="mt-2 text-2xl font-extrabold">Send a structured quotation</h1></header><div className="p-6"><div className="rounded-2xl border border-blue-100 bg-blue-50 p-4 text-sm leading-6 text-blue-950"><MessageCircleMore className="mb-2 text-blue-600" size={18} /><b>Buyer agent request:</b> Confirm the exact product/SKU, stock, GST, delivery, warranty and final payable amount. Competitor identity and pricing remain private.</div><div className="mt-5 grid gap-3 sm:grid-cols-2">{fields.map(([label, value]) => <div key={label} className="rounded-xl border border-slate-100 px-4 py-3"><p className="text-[10px] font-bold uppercase tracking-wider text-slate-400">{label}</p><p className="mt-1 text-sm font-extrabold text-slate-800">{value}</p></div>)}</div><div className="mt-5 flex flex-wrap gap-3"><button className="inline-flex items-center gap-2 rounded-xl bg-blue-600 px-4 py-3 text-sm font-bold text-white"><Send size={16} /> Send quotation</button><span className="inline-flex items-center gap-2 rounded-xl bg-emerald-50 px-4 py-3 text-xs font-bold text-emerald-700"><CheckCircle2 size={15} /> Buyer sees a comparable quote</span></div><MerchantSalesAgent /><p className="mt-5 flex gap-2 text-xs leading-5 text-slate-500"><ShieldCheck className="shrink-0 text-emerald-600" size={15} /> This merchant view demonstrates the second side of the marketplace. In production, the response is sent via WhatsApp Business, merchant app, or email.</p></div></section></div></main>;
}
