"use client";

import { useState } from "react";
import { Bot, CheckCircle2, Send, ShieldCheck, Sparkles } from "lucide-react";

type Turn = { from: "buyer" | "agent"; text: string };
const initialTurns: Turn[] = [
  { from: "buyer", text: "We need 500 ergonomic office chairs. Can you confirm stock, delivery, warranty and your best commercial terms?" },
  { from: "agent", text: "I found a matching in-stock listing: WorkFlex Ergo WFE-820. I can draft a complete response for your approval." },
];

export function MerchantSalesAgent() {
  const [turns, setTurns] = useState(initialTurns);
  const [sent, setSent] = useState(false);
  const add = (text: string) => setTurns((current) => [...current, { from: "agent", text }]);
  return <section className="mt-6 overflow-hidden rounded-2xl border border-violet-200 bg-white shadow-sm"><header className="flex flex-wrap items-center justify-between gap-3 bg-gradient-to-r from-violet-700 to-indigo-700 px-5 py-4 text-white"><div className="flex items-center gap-2"><Bot size={18} /><div><p className="text-sm font-extrabold">Merchant AI salesperson</p><p className="text-[11px] text-violet-100">Drafts replies from approved catalogue and commercial rules</p></div></div><span className="rounded-full bg-white/15 px-2.5 py-1 text-[10px] font-bold">MERCHANT-CONTROLLED</span></header><div className="p-4"><div className="max-h-52 space-y-3 overflow-auto pr-1">{turns.map((turn, index) => <div key={`${turn.from}-${index}`} className={`flex ${turn.from === "agent" ? "justify-end" : "justify-start"}`}><p className={`max-w-[88%] rounded-2xl px-3 py-2.5 text-xs leading-5 ${turn.from === "agent" ? "rounded-br-md bg-violet-600 text-white" : "rounded-bl-md bg-slate-100 text-slate-700"}`}><b className="block text-[10px] opacity-75">{turn.from === "agent" ? "Your AI salesperson" : "Buyer agent"}</b>{turn.text}</p></div>)}</div><div className="mt-4 grid gap-2 sm:grid-cols-3"><button onClick={() => add("Draft offer: 500 WorkFlex Ergo WFE-820 chairs, 820 units in stock, ₹8,250 per unit before GST, 7-business-day delivery, 3-year warranty. Please review before sending.")} className="rounded-xl border border-violet-200 px-3 py-2.5 text-left text-xs font-bold text-violet-700 hover:bg-violet-50"><Sparkles className="mb-1" size={15} /> Draft complete offer</button><button onClick={() => add("For a 500-unit order, I can propose the approved volume term: free delivery and installation support. I will not promise any extra discount without your approval.")} className="rounded-xl border border-violet-200 px-3 py-2.5 text-left text-xs font-bold text-violet-700 hover:bg-violet-50"><ShieldCheck className="mb-1" size={15} /> Handle price request</button><button onClick={() => add("Answer ready: WFE-820 has mesh lumbar support, adjustable height and tilt, with a 3-year warranty. Delivery and GST are merchant-confirmed fields.")} className="rounded-xl border border-violet-200 px-3 py-2.5 text-left text-xs font-bold text-violet-700 hover:bg-violet-50"><CheckCircle2 className="mb-1" size={15} /> Answer product Q&A</button></div><button onClick={() => setSent(true)} className="mt-3 inline-flex w-full items-center justify-center gap-2 rounded-xl bg-slate-900 py-3 text-xs font-extrabold text-white hover:bg-slate-700"><Send size={15} /> {sent ? "Structured quotation sent to buyer agent" : "Approve & send final quotation"}</button>{sent && <p className="mt-2 text-center text-[11px] font-bold text-emerald-700">Buyer receives the approved terms; the AI never sends pricing without your action.</p>}</div></section>;
}
