import type {
  AgentStep,
  AuditEvent,
  BuyerRequirement,
  Merchant,
  Quote,
} from "@/lib/types";

export const demoPrompt =
  "500–600L refrigerator under ₹70K, Samsung or LG, delivery in Bangalore by Saturday. I have an old 260L LG fridge to exchange.";

export const demoRequirement: BuyerRequirement = {
  category: "refrigerator",
  productDescription: "A 500–600L refrigerator",
  specifications: [
    "500–600L capacity",
    "Samsung or LG",
    "old 260L LG refrigerator for exchange",
  ],
  capacityMin: 500,
  capacityMax: 600,
  preferredBrands: ["Samsung", "LG"],
  maxBudget: 70000,
  deliveryCity: "Bangalore",
  deliveryBy: "Saturday",
  exchange: {
    enabled: true,
    brand: "LG",
    capacity: 260,
    ageYears: 5,
    condition: "Good",
  },
  hardConstraints: [
    "₹70,000 or less",
    "500L+ capacity",
    "Bangalore delivery",
    "Delivery by Saturday",
  ],
  preferences: [
    { criterion: "Lowest effective cost", priority: 50 },
    { criterion: "Samsung or LG", priority: 20 },
    { criterion: "Earlier delivery", priority: 20 },
    { criterion: "Warranty", priority: 10 },
  ],
  rfqGuardrails: { maxMerchants: 5, retriesPerMerchant: 1, maxFollowUps: 3 },
};

export const merchants: Merchant[] = [
  {
    id: "electrohub",
    name: "TradeHub",
    initials: "TH",
    color: "bg-violet-100 text-violet-700",
    statusLabel: "Quote received",
  },
  {
    id: "coolmart",
    name: "DealDirect",
    initials: "DD",
    color: "bg-sky-100 text-sky-700",
    statusLabel: "Doesn’t meet deadline",
  },
  {
    id: "city",
    name: "MetroSupply",
    initials: "MS",
    color: "bg-blue-600 text-white",
    statusLabel: "Recommended",
  },
  {
    id: "value",
    name: "ValueSource",
    initials: "VS",
    color: "bg-amber-100 text-amber-700",
    statusLabel: "Clarification complete",
  },
  {
    id: "hometech",
    name: "QuickFulfil",
    initials: "QF",
    color: "bg-slate-200 text-slate-600",
    statusLabel: "No response",
  },
];

export const initialQuotes: Quote[] = [
  {
    id: "q-electrohub-v1",
    merchantId: "electrohub",
    product: {
      category: "refrigerator",
      title: "530L refrigerator",
      brand: "LG",
      model: "GL-S582VPZX",
      capacityLitres: 530,
    },
    basePrice: 68000,
    gstIncluded: true,
    exchangeValue: 4000,
    effectivePrice: 64000,
    deliveryDate: "Tomorrow",
    deliveryCharge: 0,
    installationIncluded: true,
    warranty: "1 year + 10 year compressor",
    paymentConditions: "Pay on confirmation",
    validUntil: "Today, 8:00 PM",
    confidence: 98,
    missingFields: [],
    status: "VALID",
    version: 2,
    previousEffectivePrice: 65000,
  },
  {
    id: "q-coolmart-v1",
    merchantId: "coolmart",
    product: {
      category: "refrigerator",
      title: "550L refrigerator",
      brand: "Samsung",
      model: "RT56K6378SL",
      capacityLitres: 550,
    },
    basePrice: 67500,
    gstIncluded: true,
    exchangeValue: 2000,
    effectivePrice: 65500,
    deliveryDate: "Tuesday",
    deliveryCharge: 0,
    installationIncluded: true,
    warranty: "1 year + 10 year compressor",
    paymentConditions: "Pay today",
    validUntil: "Today, 9:00 PM",
    confidence: 99,
    missingFields: [],
    status: "DISQUALIFIED",
    version: 1,
  },
  {
    id: "q-city-final",
    merchantId: "city",
    product: {
      category: "refrigerator",
      title: "550L refrigerator",
      brand: "Samsung",
      model: "RT58K7108SL",
      capacityLitres: 550,
    },
    basePrice: 65500,
    gstIncluded: true,
    exchangeValue: 3000,
    effectivePrice: 62500,
    deliveryDate: "Saturday",
    deliveryCharge: 0,
    installationIncluded: true,
    warranty: "1 year + 10 year compressor",
    paymentConditions: "Pay today · offer held 30 min",
    validUntil: "30 minutes after confirmation",
    confidence: 100,
    missingFields: [],
    status: "VALID",
    version: 3,
    previousEffectivePrice: 64000,
  },
  {
    id: "q-value-v2",
    merchantId: "value",
    product: {
      category: "refrigerator",
      title: "490L refrigerator",
      brand: "Samsung",
      model: "RT49A6678S9",
      capacityLitres: 490,
    },
    basePrice: 64500,
    gstIncluded: true,
    exchangeValue: 1500,
    effectivePrice: 63000,
    deliveryDate: "Saturday",
    deliveryCharge: 0,
    installationIncluded: false,
    warranty: "1 year + 10 year compressor",
    paymentConditions: "Pay today",
    validUntil: "Today, 6:30 PM",
    confidence: 95,
    missingFields: [],
    status: "DISQUALIFIED",
    version: 2,
  },
  {
    id: "q-hometech",
    merchantId: "hometech",
    basePrice: 0,
    exchangeValue: 0,
    effectivePrice: 0,
    confidence: 0,
    missingFields: ["No merchant response after one retry"],
    status: "UNAVAILABLE",
    version: 0,
  },
];

export const progressSteps: AgentStep[] = [
  {
    id: "rfq",
    title: "RFQ sent to 5 merchants",
    detail: "Matching 500L+ Samsung and LG refrigerators in Bangalore",
    kind: "send",
    delay: 650,
  },
  {
    id: "electro",
    merchantId: "electrohub",
    title: "ElectroHub replied",
    detail: "LG 530L · ₹68,000 · delivery tomorrow",
    kind: "reply",
    delay: 850,
  },
  {
    id: "city-reply",
    merchantId: "city",
    title: "City Electronics replied",
    detail: "Samsung 550L · ₹66,000 · Saturday delivery",
    kind: "reply",
    delay: 700,
  },
  {
    id: "value-reply",
    merchantId: "value",
    title: "Value Appliances replied",
    detail: "Samsung fridge available for ₹64,500",
    kind: "reply",
    delay: 600,
  },
  {
    id: "missing",
    merchantId: "value",
    title: "Agent requested 5 missing details",
    detail: "Model, capacity, GST, delivery, warranty and exchange value",
    kind: "think",
    delay: 760,
  },
  {
    id: "cool",
    merchantId: "coolmart",
    title: "CoolMart disqualified",
    detail: "Their five-day delivery misses your Saturday deadline",
    kind: "warn",
    delay: 560,
  },
  {
    id: "home-retry",
    merchantId: "hometech",
    title: "HomeTech retry failed gracefully",
    detail: "No response after the one allowed retry — continuing",
    kind: "warn",
    delay: 620,
  },
  {
    id: "negotiate",
    merchantId: "city",
    title: "Agent negotiated with City Electronics",
    detail: "Asked to improve the exchange without revealing competing quotes",
    kind: "think",
    delay: 850,
  },
  {
    id: "city-win",
    merchantId: "city",
    title: "City Electronics improved its final offer",
    detail: "₹65,500 − ₹3,000 exchange = ₹62,500 payable",
    kind: "success",
    delay: 800,
  },
  {
    id: "ready",
    title: "Best executable offer found",
    detail: "3 comparable offers normalized; recommendation is ready",
    kind: "success",
    delay: 780,
  },
];

export const baseAuditEvents: AuditEvent[] = [
  {
    id: "a1",
    actor: "BUYER",
    action: "Buyer submitted a refrigerator request",
    reason: "Natural-language intent received",
    time: "Just now",
  },
  {
    id: "a2",
    actor: "BUYER_AGENT",
    action: "Agent created a bounded RFQ",
    reason: "Budget cap set to ₹70,000; maximum 5 merchants",
    time: "Just now",
  },
  {
    id: "a3",
    actor: "BUYER_AGENT",
    action: "Agent contacted eligible merchants",
    reason: "Each carries an in-stock 500L+ refrigerator",
    time: "Just now",
  },
  {
    id: "a4",
    actor: "BUYER_AGENT",
    action: "Agent requested missing quote fields",
    reason: "Value Appliances’ initial quote was not comparable",
    time: "Just now",
  },
  {
    id: "a5",
    actor: "SYSTEM",
    action: "Merchant timeout handled",
    reason: "HomeTech exhausted its one permitted retry; RFQ continued",
    time: "Just now",
    tone: "warning",
  },
  {
    id: "a6",
    actor: "BUYER_AGENT",
    action: "Agent negotiated exchange value",
    reason:
      "City Electronics met all constraints but could improve its effective price",
    time: "Just now",
  },
  {
    id: "a7",
    actor: "BUYER_AGENT",
    action: "Agent recommended City Electronics",
    reason: "Lowest effective qualifying offer under deterministic scoring",
    time: "Just now",
    tone: "success",
  },
];
